---
title: "Going further with Git"
subtitle: ""
author: "Nils Ratnaweera"
date: "`r Sys.Date()`"
output:
# https://stackoverflow.com/questions/51793049/xaringan-title-slide/51800826#51800826
  xaringan::moon_reader:
    css: ["default", "custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---
layout: true

# Going further with Git

---

## What's your gain from this course?

(since we only cover a fraction of Git's functionalities)


---

## What's your gain from this course?

(we help you tackle the initial hurdles)

- understanding Git's concept
- getting Git working locally
- Setting up a workflow with Github


---

## What are the <span class="highlight"> most important </span> missing pieces?

Working with ...

1. ... Git from the commandline <span class = "highlight"> (to go beyond the basics) </span>
1. ... pulls and merges\* <span class = "highlight"> (collaboration!) </span>
<!-- 1. ... Git without RStudio\*  <span class = "highlight"> (to be independent)</span> -->
1. ... branches and forks\* <span class = "highlight"> (Git's *killer features*) </span>

\* depend on (1)


---





---
class: center, middle

--

... and reaping the benefits of our hard work
 
---

- You have put much effort into learning git
- Many advantages will only reveal themselves with time
- Let's have a look at some advantages you can reap *now*

---

- Combining Rmarkdown with Github pages
- making a pull request to suggest some changes
- 






